# Generated by Django 3.2 on 2025-09-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
    ]
