# Generated by Django 3.2 on 2025-09-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_pricepolicy_project_projectuser_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#A7CE4F'), (2, '#E7DA96'), (3, '#9EBAC6'), (4, '#F79A57'), (5, '#EB4A59'), (6, '#5E595A'), (7, '#BA55D3')], default=1, verbose_name='颜色'),
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.wiki', verbose_name='父文章')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目')),
            ],
        ),
    ]
