# Generated by Django 3.2 on 2025-10-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_wiki_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default='xxxxx', max_length=128, verbose_name='cos桶'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='ap-guangzhou', max_length=32, verbose_name='cos区'),
            preserve_default=False,
        ),
    ]
