# Generated by Django 3.2 on 2025-10-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_issues_issuestype_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('😀', '高'), ('😔', '中'), ('😫', '低')], default='danger', max_length=12, verbose_name='优先级'),
        ),
    ]
